# Generated by Django 4.2 on 2023-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FinalProjectApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseData",
            fields=[
                ("courseid", models.IntegerField(primary_key=True, serialize=False)),
                ("coursetitle", models.CharField(max_length=100)),
                ("coursename", models.CharField(max_length=100)),
                ("coursesectioncode", models.IntegerField(max_length=100)),
                ("coursedepartment", models.CharField(max_length=100)),
                ("instructorname", models.CharField(max_length=100)),
            ],
        ),
    ]
