# Generated by Django 4.2 on 2023-04-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FinalProjectApp", "0002_coursedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facultyemail", models.CharField(max_length=500)),
                ("facultycomment", models.TextField()),
            ],
        ),
    ]
